/*
INSERT INTO PUBLIC.USERS (USER_NAME, USER_LOGIN, USER_EMAIL, USER_BIRTHDAY)
VALUES ('Marina', 'Marina123', 'mail@mail.ru', '1946-08-20');
*/
INSERT INTO PUBLIC.MPA_RATING (MPA_NAME)
VALUES ('G');
INSERT INTO PUBLIC.MPA_RATING (MPA_NAME)
VALUES ('PG');
INSERT INTO PUBLIC.MPA_RATING (MPA_NAME)
VALUES ('PG-13');
INSERT INTO PUBLIC.MPA_RATING (MPA_NAME)
VALUES ('R');
INSERT INTO PUBLIC.MPA_RATING (MPA_NAME)
VALUES ('NC-17');

INSERT INTO PUBLIC.GENRE (GENRE_NAME)
VALUES ('Комедия');
INSERT INTO PUBLIC.GENRE (GENRE_NAME)
VALUES ('Драма');
INSERT INTO PUBLIC.GENRE (GENRE_NAME)
VALUES ('Мультфильм');
INSERT INTO PUBLIC.GENRE (GENRE_NAME)
VALUES ('Триллер');
INSERT INTO PUBLIC.GENRE (GENRE_NAME)
VALUES ('Документальный');
INSERT INTO PUBLIC.GENRE (GENRE_NAME)
VALUES ('Боевик');

