package ru.yandex.practicum.filmorate;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import ru.yandex.practicum.filmorate.model.Film;
import ru.yandex.practicum.filmorate.model.User;
import ru.yandex.practicum.filmorate.storage.FilmDBStorage;

import java.time.LocalDate;
import java.util.List;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest()
@AutoConfigureMockMvc
@AutoConfigureTestDatabase
@RequiredArgsConstructor(onConstructor_ = @Autowired)
public class FilmControllerTests {

    @Autowired
    private MockMvc mockMvc;
    @Autowired
    private ObjectMapper objectMapper;
    @Autowired
    private final FilmDBStorage filmDBStorage;

    @Autowired
    private final JdbcTemplate jdbcTemplate;

    @AfterEach
    void clearFilms() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS PUBLIC.LIKES_TO_FILM");
        jdbcTemplate.execute("DROP TABLE IF EXISTS PUBLIC.FILMS_GENRE");
        jdbcTemplate.execute("DROP TABLE IF EXISTS PUBLIC.FILMS");
        jdbcTemplate.execute("DROP TABLE IF EXISTS PUBLIC.FRIENDS");
        jdbcTemplate.execute("DROP TABLE IF EXISTS PUBLIC.USERS");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS PUBLIC.USERS (\n" +
                "\tUSER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,\n" +
                "\tUSER_NAME VARCHAR_IGNORECASE(50),\n" +
                "\tUSER_LOGIN VARCHAR_IGNORECASE(15) NOT NULL,\n" +
                "\tUSER_EMAIL VARCHAR_IGNORECASE(50) NOT NULL,\n" +
                "\tUSER_BIRTHDAY DATE NOT NULL,\n" +
                "\tCONSTRAINT USERS_PK PRIMARY KEY (USER_ID),\n" +
                "\tCONSTRAINT UNI_LOGIN UNIQUE (USER_LOGIN)\n" +
                ");");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (\n" +
                "\tUSER_ID INTEGER NOT NULL,\n" +
                "\tFRIENDS_ID INTEGER NOT NULL,\n" +
                "\tFRIENDS_STATUS VARCHAR_IGNORECASE,\n" +
                "\tCONSTRAINT FRIENDS_FK_1 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) " +
                "ON DELETE CASCADE ON UPDATE CASCADE,\n" +
                "\tCONSTRAINT FRIENDS_FK_2 FOREIGN KEY (FRIENDS_ID) REFERENCES PUBLIC.USERS(USER_ID) " +
                "ON DELETE RESTRICT ON UPDATE RESTRICT\n" +
                ")");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (\n" +
                "\tFILM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,\n" +
                "\tFILM_NAME CHARACTER VARYING(50) NOT NULL,\n" +
                "\tFILM_DESCRIPTION CHARACTER VARYING(200) NOT NULL,\n" +
                "\tFILM_DURATION INTEGER NOT NULL,\n" +
                "\tRELEASE_DATE DATE NOT NULL,\n" +
                "\tMPA_ID INTEGER,\n" +
                "\tCONSTRAINT FILMS_MPA_RATING_FK FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA_RATING(MPA_ID) " +
                "ON DELETE CASCADE ON UPDATE CASCADE,\n" +
                "\tCONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID)\n" +
                ")");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_GENRE (\n" +
                "\tGENRE_ID INTEGER NOT NULL,\n" +
                "\tFILM_ID INTEGER NOT NULL,\n" +
                "\tCONSTRAINT FILMS_GENRE_FK_2 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) " +
                "ON DELETE CASCADE ON UPDATE CASCADE,\n" +
                "\tCONSTRAINT FILMS_GENRE_FK_3 FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID) " +
                "ON DELETE CASCADE ON UPDATE CASCADE\n" +
                ")");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS PUBLIC.LIKES_TO_FILM (\n" +
                "\tUSER_ID INTEGER,\n" +
                "\tFILM_ID INTEGER,\n" +
                "\tCONSTRAINT LIKES_TO_FILM_FK_FILM FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) " +
                "ON DELETE CASCADE ON UPDATE CASCADE,\n" +
                "\tCONSTRAINT LIKES_TO_FILM_FK_USER FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) " +
                "ON DELETE CASCADE ON UPDATE CASCADE\n" +
                ")");
    }

    @SneakyThrows
    @Test
    void filmWithGoodBehaviorTest() {
        Film film = Film.builder()
                .name("Film")
                .description("New Film")
                .releaseDate(LocalDate.of(2021, 12, 15))
                .duration(200)
                .build();
        mockMvc.perform(post("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film)))
                .andExpect(status().is(200));
    }

    @SneakyThrows
    @Test
    void filmCreateFailNameTest() {
        Film film = Film.builder()
                .name("")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1994, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film)))
                .andExpect(status().isBadRequest())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void filmCreateFailDescriptionTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescriptionFilmDescriptionFilmDescriptionFilmDescriptionFilmDescription" +
                        "FilmDescriptionFilmDescriptionFilmDescriptionFilmDescriptionFilmDescription" +
                        "FilmDescriptionFilmDescriptionFilmDescriptionFilmDescriptionFilmDescription" +
                        "FilmDescriptionFilmDescriptionFilmDescriptionFilmDescriptionFilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1994, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film)))
                .andExpect(status().isBadRequest())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void filmCreateFailRealiseDateTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1850, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film)))
                .andExpect(status().isBadRequest())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void filmCreateFailDurationTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(-1)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film)))
                .andExpect(status().isBadRequest())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void filmUpdateGoodBehaviorTest() {
        Film film1 = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film1)));
        Film film2 = Film.builder()
                .id(1L)
                .name("Name")
                .description("FilmDescription")
                .duration(140)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(put("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film2)))
                .andExpect(status().is(200))
                .andExpect(jsonPath("$.duration").value(140))
                .andExpect(jsonPath("$.id").value(1));
    }

    @SneakyThrows
    @Test
    void filmUpdateBadBehaviorTest() {
        Film film1 = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film1)));
        Film film2 = Film.builder()
                .id(999L)
                .name("Name")
                .description("FilmDescription")
                .duration(140)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(put("/films")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(film2)))
                .andExpect(status().isNotFound())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void filmGetAllTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(get("/films"))
                .andExpect(status().is(200))
                .andExpect(content().json(objectMapper.writeValueAsString(filmDBStorage.getFilms())));
    }

    @SneakyThrows
    @Test
    void filmAddLikeAndItsOkTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        User user = User.builder()
                .email("Name1@mail.ru")
                .name("Name1")
                .login("NickName1")
                .birthday(LocalDate.of(2011, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(post("/users")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(user)));
        mockMvc.perform(put("/films/1/like/1"))
                .andExpect(status().is(200))
                .andExpect(content().contentType("text/plain;charset=UTF-8"))
                .andExpect(content().string("Лайк поставлен"));
    }

    @SneakyThrows
    @Test
    void filmRemoveLikeAndItsOkTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        User user = User.builder()
                .email("Name1@mail.ru")
                .name("Name1")
                .login("NickName1")
                .birthday(LocalDate.of(2011, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(post("/users")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(user)));
        mockMvc.perform(put("/films/1/like/1"));
        mockMvc.perform(delete("/films/1/like/1"))
                .andExpect(status().is(200))
                .andExpect(content().contentType("text/plain;charset=UTF-8"))
                .andExpect(content().string("Лайк удален"));
    }

    @SneakyThrows
    @Test
    void filmRemoveLikeBadBehaviorTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        User user = User.builder()
                .email("Name1@mail.ru")
                .name("Name1")
                .login("NickName1")
                .birthday(LocalDate.of(2011, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(post("/users")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(user)));
        mockMvc.perform(put("/films/1/like/1"));
        mockMvc.perform(delete("/films/1/like/-2"))
                .andExpect(status().isNotFound())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void getFilmByIdAndItsOkTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(get("/films/1"))
                .andExpect(status().is(200))
                .andExpect(content().json(objectMapper.writeValueAsString(filmDBStorage.getFilmById(1L))));
    }

    @SneakyThrows
    @Test
    void getFilmByIdBadBehaviorTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(get("/films/999"))
                .andExpect(status().isNotFound())
                .andExpect(result -> result.getResponse().getErrorMessage());
    }

    @SneakyThrows
    @Test
    void getPopularFilmAndItsOkTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        mockMvc.perform(get("/films/popular"))
                .andExpect(status().is(200))
                .andExpect(content().json(objectMapper.writeValueAsString(filmDBStorage.getFilms())));
    }

    @SneakyThrows
    @Test
    void getMostPopularFilmAndItsOkTest() {
        Film film = Film.builder()
                .name("Name")
                .description("FilmDescription")
                .duration(150)
                .releaseDate(LocalDate.of(1950, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film)));
        User user = User.builder()
                .email("Name1@mail.ru")
                .name("Name1")
                .login("NickName1")
                .birthday(LocalDate.of(2011, 10, 7))
                .build();
        mockMvc.perform(post("/users")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(user)));
        Film film1 = Film.builder()
                .name("Name1")
                .description("FilmDescription1")
                .duration(170)
                .releaseDate(LocalDate.of(2000, 10, 7))
                .build();
        mockMvc.perform(post("/films")
                .contentType("application/json")
                .content(objectMapper.writeValueAsString(film1)));
        mockMvc.perform(put("/films/1/like/1"));
        mockMvc.perform(get("/films/popular?count=1"))
                .andExpect(status().is(200))
                .andExpect(content().json(objectMapper.writeValueAsString(List.of(filmDBStorage.getFilmById(1L)))));
    }
}
